from banksia import Metadata

__all__ = ["METADATA"]

METADATA: list[Metadata] = [
    Metadata("WEIGHT", "Weight (kg)", field_width=5, decimals=2),
    Metadata("HEIGHT", "Standing height (cm)", field_width=4, decimals=1),
    Metadata("A3", "Sitting height (cm)", field_width=4, decimals=1),
    Metadata("A4", "Head circumference (cm)", decimals=1),
    Metadata("A5", "Chest circumference (cm)", decimals=1),
    Metadata("A6", "Mid-arm circumference (cm)", decimals=1),
    Metadata("A7", "Triceps skinfold (mm)", decimals=1),
    Metadata("A8", "Subscapular skinfold (mm)", decimals=1),
    Metadata("A9", "Suprailiac skinfold (mm)", decimals=1),
    Metadata("A10", "Abdominal skinfold (mm)", decimals=1),
    Metadata("A11", "Biceps skinfold (mm)", decimals=1),
    Metadata("A12", "Waist girth (cm)", field_width=5, decimals=2),
    Metadata("A13", "Hip girth (cm)", field_width=5, decimals=2),
    Metadata("A15", "Biacromial width (cm)", field_width=4, decimals=2),
    Metadata("A16", "ASIS width (cm)", field_width=4, decimals=2),
    Metadata("A17", "Left wrist width (cm)", field_width=2, decimals=1),
    Metadata("A18", "Right rib skinfold (mm)", field_width=4, decimals=2),
    Metadata("A19", "Finger length - left hand second digit (mm)", field_width=4, decimals=2),
    Metadata("A20", "Finger length - left hand fourth digit (mm)", field_width=4, decimals=2),
    Metadata("A21", "Finger length - right hand second digit (mm)", field_width=4, decimals=2),
    Metadata("A22", "Finger length - right hand fourth digit (mm)", field_width=4, decimals=2),
    Metadata("A23", "Right wrist width (cm)", field_width=2, decimals=1),
    Metadata("BMI", "Body mass index", field_width=4, decimals=2),
    Metadata("BP1", "Systolic blood pressure"),
    Metadata("BP2", "Diastolic blood pressure"),
    Metadata(
        "BP3",
        "Blood pressure state",
        var_type="nominal",
        field_values={1: "Quiet/relaxed", 2: "Excited/agitated", 3: "Crying"},
    ),
    Metadata(
        "BP4",
        "Blood pressure instrument",
        var_type="nominal",
        field_values={
            1: "Mercury sphygmomanometer",
            2: "Aneroid sphygmomanometer",
            3: "Dinamap BP recorder",
            4: "Other electronic device (e.g. infrasound)",
            5: "Other (e.g. manual palpitation)",
        },
    ),
    Metadata("BP5", "Heart rate"),
    Metadata("BP46", "Systolic blood pressure (resting/seated) - 0 mins"),
    Metadata("BP47", "Diastolic blood pressure (resting/seated) - 0 mins"),
    Metadata("BP48", "Heart rate (resting/seated) - 0 mins"),
    Metadata("BP49", "Systolic blood pressure (resting/seated) - 2 mins"),
    Metadata("BP50", "Diastolic blood pressure (resting/seated) - 2 mins"),
    Metadata("BP51", "Heart rate (resting/seated) - 2 mins"),
    Metadata("BP52", "Systolic blood pressure (resting/seated) - 4 mins"),
    Metadata("BP53", "Diastolic blood pressure (resting/seated) - 4 mins"),
    Metadata("BP54", "Heart rate (resting/seated) - 4 mins"),
    Metadata("BP55", "Systolic blood pressure (resting/seated) - 6 mins"),
    Metadata("BP56", "Diastolic blood pressure (resting/seated) - 6 mins"),
    Metadata("BP57", "Heart rate (resting/seated) - 6 mins"),
    Metadata("BP58", "Systolic blood pressure (resting/seated) - 8 mins"),
    Metadata("BP59", "Diastolic blood pressure (resting/seated) - 8 mins"),
    Metadata("BP60", "Heart rate (resting/seated) - 8 mins"),
    Metadata("BP61", "Systolic blood pressure (resting/seated) - 10 mins"),
    Metadata("BP62", "Diastolic blood pressure (resting/seated) - 10 mins"),
    Metadata("BP63", "Heart rate (resting/seated) - 10 mins"),
    Metadata("BP64", "Systolic blood pressure (supine) - 0 mins"),
    Metadata("BP65", "Diastolic blood pressure (supine) - 0 mins"),
    Metadata("BP66", "Heart rate (supine) - 0 mins"),
    Metadata("BP67", "Systolic blood pressure (supine) - 2 mins"),
    Metadata("BP68", "Diastolic blood pressure (supine) - 2 mins"),
    Metadata("BP69", "Heart rate (supine) - 2 mins"),
    Metadata("BP70", "Systolic blood pressure (supine) - 4 mins"),
    Metadata("BP71", "Diastolic blood pressure (supine) - 4 mins"),
    Metadata("BP72", "Heart rate (supine) - 4 mins"),
    Metadata("BP73", "Systolic blood pressure (supine) - 6 mins"),
    Metadata("BP74", "Diastolic blood pressure (supine) - 6 mins"),
    Metadata("BP75", "Heart rate (supine) - 6 mins"),
    Metadata("BP76", "Systolic blood pressure (supine) - 8 mins"),
    Metadata("BP77", "Diastolic blood pressure (supine) - 8 mins"),
    Metadata("BP78", "Heart rate (supine) - 8 mins"),
    Metadata("BP79", "Systolic blood pressure (supine) - 10 mins"),
    Metadata("BP80", "Diastolic blood pressure (supine) - 10 mins"),
    Metadata("BP81", "Heart rate (supine) - 10 mins"),
    Metadata(
        "BPCD",
        "Blood pressure code",
        var_type="nominal",
        field_width=1,
        field_values={
            0: "No abnormality detected",
            1: "Pregnant",
            2: "Increased blood pressure (hypertensive)",
        },
    ),
    Metadata("BP_TEMP", "Temperature of assessment room (C)", decimals=1),
    # Metadata(
    #     "BP_TIME",
    #     "Time of blood pressure assessment",
    #     field_type="Time",
    #     field_width=8,
    #     decimals=0,
    # ),
    Metadata(
        "BP_CUFF",
        "Size of cuff for blood pressure",
        var_type="nominal",
        field_width=1,
        field_values={1: "Small", 2: "Medium", 3: "Large", 4: "Extra large/thigh"},
    ),
]
